const VARENYA_POSTS_BOX = "VARENYA_POSTS_BOX";
const VARENYA_POST_CATEGORY_BOX = "VARENYA_POST_CATEGORY_BOX";
const VARENYA_DOCTORS_BOX = "VARENYA_DOCTORS_BOX";
const VARENYA_SPECIALIZATION_BOX = "VARENYA_SPECIALIZATION_BOX";
const VARENYA_JOB_BOX = "VARENYA_JOB_BOX";
const VARENYA_APPOINTMENT_BOX = "VARENYA_APPOINTMENT_BOX";

const VARENYA_APPOINTMENT_LIST = "VARENYA_APPOINTMENT_LIST";
const VARENYA_FILTERED_DOCTORS_LIST = "VARENYA_FILTERED_DOCTORS_LIST";
const VARENYA_SPECIALIZATION_LIST = "VARENYA_SPECIALIZATION_LIST";
const VARENYA_JOB_LIST = "VARENYA_JOB_LIST";
const VARENYA_CATEGORY_LIST = "VARENYA_CATEGORY_LIST";
